"""
Experiment constants.
"""


IDENTITY_MAPPER = "identity-mapper"
AVERAGE_REWARD_MAPPER = "average-reward-mapper"
REWARD_ESTIMATION_LSQ_MAPPER = "reward-estimation-lsq-mapper"
REWARD_IMPUTATION_MAPPER = "reward-imputation-mapper"
MDP_WITH_OPTIONS_MAPPER = "mdp-with-options-mapper"
NSTEP_AGGREGATE_MAPPER = "nstep-aggregate-feedback-mapper"
AGGREGATE_MAPPER_METHODS = (
    IDENTITY_MAPPER,
    AVERAGE_REWARD_MAPPER,
    REWARD_IMPUTATION_MAPPER,
    REWARD_ESTIMATION_LSQ_MAPPER,
    MDP_WITH_OPTIONS_MAPPER,
)
OPTIONS_POLICY = "options"
SINGLE_STEP_POLICY = "single-step"

DEFAULT_BUFFER_SIZE_MULTIPLIER = 2**8
DEFAULT_NUM_EPISODES_FOR_REF_ESTIMATION = 10_000

SARSA = "sarsa"
ONE_STEP_TD = "one-step-td"
FIRST_VISIT_MONTE_CARLO = "first-visit-mc"
NSTEP_TD = "nstep-td"
ALGORITHMS = (ONE_STEP_TD, FIRST_VISIT_MONTE_CARLO, NSTEP_TD)
